<?php 
namespace PrimeKit\Admin\Inc\Dashboard\Settings;

if (!defined('ABSPATH')) exit; // Exit if accessed directly

class Settings {

    public function __construct() {
        // Hook for adding the settings page to the admin menu
        add_action('admin_menu', [$this, 'add_settings_page']);
        
        // Hook for registering settings
        add_action('admin_init', [$this, 'register_settings']);
    }

    public function add_settings_page() {
        add_menu_page(
            __('PrimeKit Settings', 'primekit-addons'),
            __('PrimeKit Settings', 'primekit-addons'),
            'manage_options',
            'primekit_settings',
            [$this, 'render_settings_page'],
            'dashicons-admin-generic'
        );
    }

    public function render_settings_page() {
        ?>
        <div class="wrap">
            <h1><?php _e('PrimeKit Settings', 'primekit-addons'); ?></h1>
            <form method="post" action="options.php">
                <?php
                    settings_fields('primekit_addons_options_group'); // Nonce generated by WordPress for options group
                    do_settings_sections('primekit_settings');
                    submit_button();
                ?>
            </form>
        </div>
        <?php
    }

    public function register_settings() {
        register_setting('primekit_addons_options_group', 'primekit_option_name', [
            'sanitize_callback' => [$this, 'sanitize_option_name']
        ]);

        add_settings_section(
            'primekit_addons_section',
            __('Main Settings', 'primekit-addons'),
            null,
            'primekit_settings'
        );

        add_settings_field(
            'primekit_option_name',
            __('Option Name', 'primekit-addons'),
            [$this, 'display_option_name_field'],
            'primekit_settings',
            'primekit_addons_section'
        );
    }

    public function sanitize_option_name($input) {
        // Sanitize user input (e.g., strip tags and escape)
        return sanitize_text_field($input);
    }

    public function display_option_name_field() {
        // Display the option with a nonce field for security
        $option = get_option('primekit_option_name');
        wp_nonce_field('primekit_addons_save_settings', 'primekit_addons_nonce');
        echo "<input type='text' name='primekit_option_name' value='" . esc_attr($option) . "' />";
    }
}